#!/bin/bash

array=()
vmname=()
## source openrc file ##
source /root/.open-rc

## Set in b/w range to fetch vm ###
start=0      
end=5
## convert to array to fetch vm ###
while IFS='' read -r vm; do vmname+=("$vm"); done < <(openstack --insecure server list --all-projects --long | awk 'NR>=4 {print $4}')

## limit in b/w range to backup vm list ###
for i in "${vmname[@]:start:end}"; do
    if [[ ! -e /disk1/"$i" ]]; then
        mkdir -p /disk1/"$i"
    fi
    for j in $(nova --insecure list --all-tenants --status=Active | grep "$i" | awk 'NR<=1 {print $2}'); do
        while IFS='' read -r line; do array+=("$line"); done < <(rbd ls -p cinder-ceph | grep "$j"_disk)
        for ID in "${array[@]}"; do
            for w in $(nova --insecure list --all-tenants | grep "$i" | awk 'NR<=1 {print $8}'); do
                if [ "$w" == "shutoff" ];
                then
                   echo "[INFO] $i is in Shutoff state... skipping"
                   break 1
                elif [ "$ID" == "$j"_disk ] ;
                then
                   rbd snap create cinder-ceph/$ID@$ID && rm -rf /disk1/"$i"/"$ID".img && rbd export cinder-ceph/$ID@$ID /disk1/"$i"/"$ID".img && rbd snap rm cinder-ceph/$ID@$ID
                   continue
                fi
            done
        done
    done
done
